// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsMysql "github.com/kuetix/std-mysql/modules/mysql/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["mysql"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"mysql"+"/"+"database", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "database", Impl: transitionsMysql.NewDatabaseTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"mysql"+"/"+"exec", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "exec", Impl: transitionsMysql.NewExecTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"mysql"+"/"+"query", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "query", Impl: transitionsMysql.NewQueryTransitions() }})
	}
}
