// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"mysql": {
			"query": {
				"Query": {
					GoModule: "github.com/kuetix/std-mysql",
					ModulePath: "modules",
					FilePath: "modules/mysql/transitions/query.go",
					Namespace: "query",
					Class: "mysql",
					Name: "Query",
					NumIn: 3,
					NumOut: 1,
					ArgTypes: []string{"string", "string", "[]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"dsn", "sqlText", "args"},
					ReturnNames: []string{"r"},
				},
				"QueryRow": {
					GoModule: "github.com/kuetix/std-mysql",
					ModulePath: "modules",
					FilePath: "modules/mysql/transitions/query.go",
					Namespace: "query",
					Class: "mysql",
					Name: "QueryRow",
					NumIn: 3,
					NumOut: 1,
					ArgTypes: []string{"string", "string", "[]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"dsn", "sqlText", "args"},
					ReturnNames: []string{"r"},
				},
			},
			"database": {
				"Ping": {
					GoModule: "github.com/kuetix/std-mysql",
					ModulePath: "modules",
					FilePath: "modules/mysql/transitions/database.go",
					Namespace: "database",
					Class: "mysql",
					Name: "Ping",
					NumIn: 1,
					NumOut: 1,
					ArgTypes: []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"dsn"},
					ReturnNames: []string{"r"},
				},
			},
			"exec": {
				"Exec": {
					GoModule: "github.com/kuetix/std-mysql",
					ModulePath: "modules",
					FilePath: "modules/mysql/transitions/exec.go",
					Namespace: "exec",
					Class: "mysql",
					Name: "Exec",
					NumIn: 3,
					NumOut: 1,
					ArgTypes: []string{"string", "string", "[]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"dsn", "sqlText", "args"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}

